# Generated by Django 3.1 on 2021-07-26 12:24

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=250, verbose_name='Ник пользователя')),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение пользователя')),
                ('post_link', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на пост')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение поста')),
                ('like_count', models.CharField(blank=True, max_length=250, verbose_name='Количество лайков')),
                ('active', models.BooleanField(default=False, verbose_name='Отображать пост?')),
            ],
            options={
                'verbose_name': 'Пост Instagram',
                'verbose_name_plural': 'Посты Instagram',
                'ordering': ('-like_count',),
            },
        ),
    ]
